server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/base_app?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
logging:
  level:
    root: info
  path: ./logs
mybatis:
  configuration:
    map-underscore-to-camel-case: true